name: integration

env:
  DENO_VERSION: 1.x

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/*.lua"
      - "**/*.vim"
      - ".github/workflows/integration.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ts"
      - "**/*.lua"
      - "**/*.vim"
      - ".github/workflows/integration.yml"

jobs:
  # It does not work currently.
  # https://github.com/leafo/gh-actions-lua/issues/47
  #check:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: denoland/setup-deno@v1
  #      with:
  #        deno-version: ${{ env.DENO_VERSION }}
  #    - uses: leafo/gh-actions-lua@v10
  #      with:
  #        luaVersion: "luajit-2.1.0-beta3"
  #    - uses: leafo/gh-actions-luarocks@v4
  #    - run: luarocks install luacheck

  #    - name: Check
  #      run: deno task check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "./repo"
      - uses: actions/checkout@v4
        with:
          repository: "vim-denops/denops.vim"
          path: "./denops.vim"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - uses: rhysd/action-setup-vim@v1
        with:
          version: nightly
          neovim: true
      - name: Test
        run: deno task test
        env:
          DENOPS_TEST_DENOPS_PATH: "../denops.vim"
        working-directory: ./repo
